### ISSUE TITLE
Agregar por distrito

### ISSUE THREAD

**Issue by jfoclpf** [jfoclpf/geoptapi#21]
Criar um route `/distrito`

- apenas `/distrito` lista os distritos
- `/distrito/municipios` lista árvore de distritos com municípios
- `/distrito/municipios/freguesias` lista árvore de distritos com municípios com freguesias

**Comment by jfoclpf** [comment]
sim @waldyrious, ambos funcionarão 

no express teremos algo

```js
app.get(['/distrito', '/distritos'], function (req, res, next) {
```

**Comment by jfoclpf** [comment]
na realidade faremos com regex

```js
app.get(/^\/distritos?$/, function (req, res)
``` 
```js
app.get(/^\/distritos?\/freguesias?$/, function (req, res) 
```

```js
app.get(/^\/distritos?\/municipios?\/freguesias?$/, function (req, res)
```

**Comment by jfoclpf** [comment]
Feito:
https://geoptapi.org/distritos
https://geoptapi.org/distritos/municipios

não vale a pena fazer  `/distritos/municipios/freguesias` pois é facilmente combinável com `/municipios/freguesias`

**Comment by waldyrious** [comment]
> não vale a pena fazer `/distritos/municipios/freguesias` pois obtêm-se facilmente através de `/municipios/freguesias`

Hmm, no `/municipios/freguesias` está tudo numa lista única (freguesias dentro de municípios, mas todos os municípios na raiz). Não seria útil ter o `/distritos/municipios/freguesias` como forma de obter a mesma listagem mas com 3 níveis, isto é, com os municípios agregados nos distritos correspondentes?

**Comment by jfoclpf** [comment]
Julgo que não há utilidade, não vejo que alguém dê uso a esse pedido, que
não consiga fazer facilmente com os outros dois pedidos
