### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by carlosefonseca** [jfoclpf/geoptapi#23]
👋 Boas! Só para informar que o serviço está a dar `502 Bad Gateway`.
Já agora, obrigado pelo serviço que tem sido útil para ajudar a estruturar informações pessoais 👍

**Comment by jfoclpf** [comment]
Obrigado pelo aviso, já está operacional.

já agora, que tipo de informações pessoais estás a estrutura? Apenas por curiosidade!

**Comment by carlosefonseca** [comment]
Obrigado!
Tenho estado a criar uma BD pessoal de locais e uso a API para obter a freguesia/concelho/distrito da coordenada do local para ajudar a estruturar a informação.

**Comment by jfoclpf** [comment]
Fixe! Qualquer problema avisa.

Carlos Fonseca ***@***.***> schrieb am Mo., 8. Nov. 2021,
13:01:
