### ISSUE TITLE
Sugestão - Retornar dicofre

### ISSUE THREAD

**Issue by bento-martins** [jfoclpf/geoptapi#28]
Excelente webAPI e iniciativa! Sugeria apenas retornar também o código **dicofre** pois é o identificador único de uma Freguesia. Esta informação vem na CAOP e permite fazer a comparação com outros dados, de outras aplicações, não por uma string mas por um valor inteiro inequívoco. 
Obrigado pela geoptapi!

**Comment by jfoclpf** [comment]
Ok, fá-lo-ei, não é difícil, eu retirei o dicofre pois pensei que era inútil

**Comment by bento-martins** [comment]
Muito obrigado! Pessoalmente dá-me jeito, mas acho que é uma mais valia para todos, para vários fins. A DGT disponibiliza dados que normalmente contêm o dicofre. Tendo as coordenadas de um ponto, identificando o dicofre com esta API facilmente se encontra a associação nos dados da DGT. Por exemplo:
A tua API retorna "União das freguesias de Reguengo e São Julião" e o dicofre 121412. Noutros dados poderá estar "UF Reguengo e S. Julião", sendo mais complicado fazer a associação por essa string. Se ambos tiverem o dicofre a identificação é perfeita.

**Comment by jfoclpf** [comment]
Boas, podes ver o ficheiro em bruto das freguesias
https://raw.githubusercontent.com/jfoclpf/geoptapi/main/res/details-parishes-municipalities/detalhesFreguesiasA.json

referes-te ao campo `codigo`?

Apenas para confirmar

**Comment by jfoclpf** [comment]
Não será o campo `codigo` que já aparece?

https://geoptapi.org/freguesia?nome=serzedelo&municipio=guimar%C3%A3es

**Comment by bento-martins** [comment]
Refiro-me ao campo dicofre que vem na tabela da CAOP.

![image](https://user-images.githubusercontent.com/34031305/152529333-09b48771-e670-4a77-9fb9-8a716f653693.png)

Pela análise desses dados é semelhante ao código codigoine. Já fui confirmar com uma série de freguesias. Se já tem o codigoine é mais que suficiente. O único senão é que a CAOP geralmente está mais atualizada que os códigos que o INE usa, mas isso é só se houver uma agregação de freguesias ou alterações a esse nível. Desculpa o incómodo, vou utilizar esse codigoine. 

Reitero mais uma vez: excelente projeto!

**Comment by jfoclpf** [comment]
ah, sim, o código INE é igual ao dicofre que vem na CAOP, aliás é isso que eu uso para mesclar (merge) a informação bruta que vem dessas duas fontes diferentes.

Se entretanto houver alteração ou atualização de freguesias, diz-me que eu atualizo o projeto

vou então fechar o tópico e fico agradecido que te seja útil
