### ISSUE TITLE
/municipios/{nome}/freguesias

### ISSUE THREAD

**Issue by lionyouko** [jfoclpf/geoptapi#32]
Olá,
Poderia por gentileza implementar o caminho acima em que traga a lista de freguesias sem detalhes parecido com /municipios/freguesias, mas só para um município?

Assim não é preciso filtrar a lista inteira por nome, nem ter de filtrar por detalhes de json objects representando toda uma freguesia.

Exemple de resposta que eu gostaria desse endpoint:
/municipios/abrantes/freguesias traria:

   {
      "freguesias":[
         "Bemposta",
         "Carvalhal",
         "Fontes",
         "Martinchel",
         "Mouriscas",
         "Pego",
         "Rio de Moinhos",
         "Tramagal",
         "União das freguesias de Abrantes (São Vicente e São João) e Alferrarede",
         "União das freguesias de Aldeia do Mato e Souto",
         "União das freguesias de Alvega e Concavada",
         "União das freguesias de São Facundo e Vale das Mós",
         "União das freguesias de São Miguel do Rio Torto e Rossio ao Sul do Tejo"
      ]
   }

Obrigado,

**Comment by jfoclpf** [comment]
Olá, sim, parece facilmente fazível.
Quando tiver um tempinho faço isso

**Comment by lionyouko** [comment]
Muito obrigado

**Comment by jfoclpf** [comment]
Boas, aqui tem, exemplo:

https://geoptapi.org/municipio/Beja/freguesias
https://geoptapi.org/municipio/Lisboa/freguesias

qualquer dúvida ou sugestão de melhoria, diga
